POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwiaWQiOiI2NDI4Nzc2NTdiNDhlNjdjMTdlZTdlZTYiLCJpYXQiOjE2ODAzNzQyMjZ9.SxwJv52LyeGnoJss8t-nQplxhdwSt_ke1L5forwHPKQ

{
    "content": "Using token authorization",
    "important": true
}