POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlVG9rZW4iLCJpZCI6IjY0MjliZmNmZTlhZDRhODYzZWNlYmZjNSIsImlhdCI6MTY4MDQ1NzgwNX0.GCnvEN1kP0VcEcaVQ_G4S6FaUofGBfYHpYZAfUCGhtk

{
    "title": "testeUserExtractorMiddleware",
    "author": "testeUserExtractorMiddleware",
    "url": "testeUserExtractorMiddleware",
    "likes": 2
}